### ISSUE TITLE
cant perform file upload using Apache 2.4.10

### ISSUE THREAD

**Issue by leokaplan** [Etiene/sailor#31] opened 2015-01-28 17:03 UTC
r:parsebody() returns two tables; The first one is a single-value key->pair list, the second one contains values as a list of items.

```lua
function handle(r)
  local single, multiple = r:parsebody(10240)
  r:puts(table.concat(multiple['b'] or {}, "-")) -- prints out "foo-bar" if b exists
  return apache2.OK
end
```

**Comment by Etiene** [comment] 2015-01-28 17:06
This is a mod_lua issue and I believe it has already been addressed. What's your apache version?

**Comment by leokaplan** [comment] 2015-01-28 17:13
2.4.2, as told in the installation manual. 

it is written in sailor.lua: 
    if r.parsebody ~= nil then -- only present in Apache 2.4.3 or higher

is apache 2.4.3 a requirement for doing file upload?

**Comment by leokaplan** [comment] 2015-01-28 17:15
2.4.10

**Comment by afbranco** [comment] 2015-01-28 20:00
Hi Etiene,
Some more details about the problem.
When I use enctype="multipart/form-data" in the form tag, the POST and POSTMULTI are empty.
If I remove the enctype, the name field of \<input type="file"\> of POST comes with original file name.
I'm using Ubuntu 12.04 and Apache 2.4.10 from PPA http://ppa.launchpad.net/ondrej/php5/ubuntu

**Comment by afbranco** [comment] 2015-02-01 19:38
**From mod_lua documentation:**
* r:parsebody([sizeLimit]) -- parse the request body as a POST and return two lua tables, just like r:parseargs(). An optional number may be passed to specify the maximum number of bytes to parse. Default is 8192 bytes. 

I was trying a file size near the 8kb and the POST was empty. Now, when I try a small file, I got "The connection was reset" in the web page. The apache2/error.log have an entry: AH00051: child pid 31577 exit signal Segmentation fault (11), possible coredump in /etc/apache2

1) Is it possible to have an option in Sailor to define a default [sizeLimit] to parsebody()?
2) Is needed some special configuration to use file upload?

**Comment by Etiene** [comment] 2015-02-03 13:00
Thank you for your details. I'll take a deep look at it

**Comment by Etiene** [comment] 2015-02-06 15:02
When I try page.r:parsebody([sizeLimit]) on sailor everything seems to be working fine. However when trying page.POST it will not work because by default sailor does not set a max file size and sends nothing as a parameter. I'll fix that soon, adding an option on conf.lua, but I really don't understand why parse body is not working for you... here is a code example I ran right now.

controllers/test.lua
```lua
local test ={}
function test.index(page)
    local POST = page.r:parsebody(1024*1024)
	if POST.datafile then
		file = io.open ('/Users/ecdalcol/Desktop/tuxedo/test' , 'w')
		io.output(file)
        io.write(POST.datafile)
        io.close(file)
	end
	page:render('index')
end
return test
```

views/test/index.lp 
```html
<form enctype="multipart/form-data" method="post">
	<input type="file" name="datafile">
	<input type="submit" value="Send">
</form>
```

I tried uploading an image and it worked just fine. I'm having another issue though which is that I can't seem to find out how to obtain the file name. I'll try to contact Daniel from mod_lua about that and come back :)

**Comment by Etiene** [comment] 2015-02-07 06:55
Yea, it seems that the filename is not obtainable for now. I think this could be solved with some javascript hack but it's not optimal. It's maybe time to contribute to mod_lua! :dancer: I'll try to take a look at that, but I guess this is not about your main issue, so please update on how it is going over there and if I can close this issue.

**Comment by afbranco** [comment] 2015-02-08 14:16
1) Your example also doesn't work for me. I tried a fresh instalation with ubuntu 14.10 and I had the same error. The Ubuntu crash report pointed **lfs.so** as the problem. Is it a directory authorization that is missing?
2) About the filename issue, I'm not using the filename.

**Comment by Etiene** [comment] 2015-02-08 15:22
Can you copy here the crash report? Also, like leokaplan, are you using apache 2.4.10 or higher?

**Comment by afbranco** [comment] 2015-02-08 19:10
I sent the crash report file by e-mail.
I built a fresh instalation using Ubuntu 14.10, Apache 2.4.10, Lua 5.1. Everything from Software Center.
I'm suspecting that it is a configuration problem!
What are your configurations for /etc/apache2/apache2.conf? And which *chown* command I have to apply?

**Comment by afbranco** [comment] 2015-02-16 13:43
Hi, it is working now! :+1: 
Apparently the problem is with Ubuntu 32bit.
I tested now in Ubuntu 14.04 and 14.10 64-bit server and the file-upload worked.
The problem that I had to work around is that the second parsebody() comes empty when the first works. This happens when the file is very small and does not exceed the default limit.

**Comment by Etiene** [comment] 2015-02-18 12:43
Thanks for all the info! I'm glad it's working out now! :D

**Closed** 2015-02-27 07:48 UTC
